#!/usr/bin/ruby


#--------------------------
#
# @module ListsOfThings
#
# @desc Responsibility: Has Lists of things (birds, animals...) that can be used to generate fake data
#
#
# @author Ashley Engelund (ashley.engelund@gmail.com  weedySeaDragon @ github)
# @date   2019-04-09
#
# @file lists_of_things.rb
#
#--------------------------


module ListsOfThings


  BIRDS = ["Fulvous Whistling-Duck",
                "Greater White-fronted Goose",
                "Emperor Goose",
                "Snow Goose",
                "Ross’s Goose",
                "Brant",
                "Cackling Goose",
                "Canada Goose",
                "Tundra Swan",
                "Wood Duck",
                "Blue-winged Teal",
                "Cinnamon Teal",
                "Northern Shoveler",
                "Gadwall",
                "Falcated Duck",
                "Eurasian Wigeon",
                "American Wigeon",
                "Mallard",
                "American Black Duck",
                "Northern Pintail",
                "Green-winged Teal",
                "Canvasback",
                "Redhead",
                "Ring-necked Duck",
                "Tufted Duck",
                "Greater Scaup",
                "Lesser Scaup",
                "Harlequin Duck",
                "Surf Scoter",
                "White-winged Scoter",
                "Long-tailed Duck",
                "Bufflehead",
                "Common Goldeneye",
                "Barrow’s Goldeneye",
                "Hooded Merganser",
                "Common Merganser",
                "Red-breasted Merganser",
                "Ruddy Duck",
                "Mountain Quail",
                "Scaled Quail",
                "California Quail",
                "Gambel’s Quail",
                "Montezuma Quail",
                "Chukar",
                "Ring-necked Pheasant",
                "Willow Ptarmigan",
                "Wild Turkey",
                "Pied-billed Grebe",
                "Horned Grebe",
                "Red-necked Grebe",
                "Eared Grebe",
                "Western Grebe",
                "Clark’s Grebe",
                "Rock Pigeon",
                "Band-tailed Pigeon",
                "Eurasian Collared-Dove",
                "Inca Dove",
                "Common Ground-Dove",
                "White-winged Dove",
                "Mourning Dove",
                "Yellow-billed Cuckoo",
                "Greater Roadrunner",
                "Common Nighthawk",
                "Vaux’s Swift",
                "White-throated Swift",
                "Rivoli’s Hummingbird",
                "Plain-capped Starthroat",
                "Blue-throated Hummingbird",
                "Lucifer Hummingbird",
                "Black-chinned Hummingbird",
                "Anna’s Hummingbird",
                "Costa’s Hummingbird",
                "Broad-tailed Hummingbird",
                "Rufous Hummingbird",
                "Allen’s Hummingbird",
                "Calliope Hummingbird",
                "Broad-billed Hummingbird",
                "Violet-crowned Hummingbird",
                "White-eared Hummingbird",
                "California Black Rail",
                "Ridgway’s Rail",
                "King Rail",
                "Virginia Rail",
                "Sora",
                "Purple Gallinule",
                "Common Gallinule",
                "American Coot",
                "Limpkin",
                "Sandhill Crane",
                "Black-necked Stilt",
                "American Avocet",
                "Black Oystercatcher",
                "Black-bellied Plover",
                "American Golden-Plover",
                "Pacific Golden-Plover",
                "Greater Sand-Plover",
                "Western Snowy Plover",
                "Wilson’s Plover",
                "Semipalmated Plover",
                "Piping Plover",
                "Killdeer",
                "Mountain Plover",
                "Eurasian Dotterel",
                "Whimbrel",
                "Long-billed Curlew",
                "Bar-tailed Godwit",
                "Hudsonian Godwit",
                "Marbled Godwit",
                "Ruddy Turnstone",
                "Black Turnstone",
                "Red Knot",
                "Surfbird",
                "Ruff",
                "Sharp-tailed Sandpiper",
                "Stilt Sandpiper",
                "Long-toed Stint",
                "Sanderling",
                "Dunlin",
                "Rock Sandpiper",
                "Baird’s Sandpiper",
                "Least Sandpiper",
                "White-rumped Sandpiper",
                "Buff-breasted Sandpiper",
                "Pectoral Sandpiper",
                "Semipalmated Sandpiper",
                "Western Sandpiper",
                "Short-billed Dowitcher",
                "Long-billed Dowitcher",
                "Wilson’s Snipe",
                "Spotted Sandpiper",
                "Solitary Sandpiper",
                "Wandering Tattler",
                "Lesser Yellowlegs",
                "Willet",
                "Greater Yellowlegs",
                "Wilson’s Phalarope",
                "Red-necked Phalarope",
                "Red Phalarope",
                "Great Skua",
                "South Polar Skua",
                "Pomarine Jaeger",
                "Parasitic Jaeger",
                "Long-tailed Jaeger",
                "Common Murre",
                "Razorbill",
                "Pigeon Guillemot",
                "Marbled Murrelet",
                "Scripps’s Murrelet",
                "Cassin’s Auklet",
                "Parakeet Auklet",
                "Least Auklet",
                "Crested Auklet",
                "Rhinoceros Auklet",
                "Atlantic Puffin",
                "Horned Puffin",
                "Tufted Puffin",
                "Swallow-tailed Gull",
                "Black-legged Kittiwake",
                "Sabine’s Gull",
                "Bonaparte’s Gull",
                "Little Gull",
                "Laughing Gull",
                "Ross’s Gull",
                "Franklin’s Gull",
                "Heermann’s Gull",
                "Mew Gull",
                "Ring-billed Gull",
                "Western Gull",
                "California Gull",
                "Herring Gull",
                "Iceland Gull",
                "Lesser Black-backed Gull",
                "Glaucous-winged Gull",
                "Glaucous Gull",
                "Great Black-backed Gull",
                "Least Tern",
                "Caspian Tern",
                "Black Tern",
                "Common Tern",
                "Arctic Tern",
                "Forster’s Tern",
                "Royal Tern",
                "Sandwich Tern",
                "Elegant Tern",
                "Black Skimmer",
                "Red-throated Loon",
                "Arctic Loon",
                "Pacific Loon",
                "Common Loon",
                "Yellow-billed Loon",
                "Laysan Albatross",
                "Black-footed Albatross",
                "Short-tailed Albatross",
                "Northern Fulmar",
                "Black-capped Petrel",
                "Hawaiian Petrel",
                "Fea’s Petrel",
                "Cory’s Shearwater",
                "Buller’s Shearwater",
                "Short-tailed Shearwater",
                "Sooty Shearwater",
                "Great Shearwater",
                "Pink-footed Shearwater",
                "Flesh-footed Shearwater",
                "Manx Shearwater",
                "Black-vented Shearwater",
                "Wilson’s Storm-Petrel",
                "Fork-tailed Storm-Petrel",
                "Leach’s Storm-Petrel",
                "Ashy Storm-Petrel",
                "Band-rumped Storm-Petrel",
                "Black Storm-Petrel",
                "Wood Stork",
                "Brown Booby",
                "Brandt’s Cormorant",
                "Neotropic Cormorant",
                "Double-crested Cormorant",
                "Pelagic Cormorant",
                "Anhinga",
                "American White Pelican",
                "Brown Pelican",
                "American Bittern",
                "Least Bittern",
                "Great Blue Heron",
                "Great Egret",
                "Snowy Egret",
                "Tricolored Heron",
                "Reddish Egret",
                "Cattle Egret",
                "Green Heron",
                "Black-crowned Night-Heron",
                "Yellow-crowned Night-Heron",
                "White Ibis",
                "Glossy Ibis",
                "White-faced Ibis",
                "Roseate Spoonbill",
                "Black Vulture",
                "Turkey Vulture",
                "Osprey",
                "White-tailed Kite",
                "Swallow-tailed Kite",
                "Golden Eagle",
                "Northern Harrier",
                "Sharp-shinned Hawk",
                "Cooper’s Hawk",
                "Bald Eagle",
                "Harris’s Hawk",
                "Gray Hawk",
                "Red-shouldered Hawk",
                "Broad-winged Hawk",
                "Swainson’s Hawk",
                "Zone-tailed Hawk",
                "Red-tailed Hawk",
                "Rough-legged Hawk",
                "Ferruginous Hawk",
                "Barn Owl",
                "Western Screech-Owl",
                "Eastern Screech-Owl",
                "Whiskered Screech-Owl",
                "Great Horned Owl",
                "Northern Pygmy-Owl",
                "Elf Owl",
                "Burrowing Owl",
                "Spotted Owl",
                "Barred Owl",
                "Long-eared Owl",
                "Short-eared Owl",
                "Northern Saw-whet Owl",
                "Elegant Trogon",
                "Belted Kingfisher",
                "Lewis’s Woodpecker",
                "Acorn Woodpecker",
                "Gila Woodpecker",
                "Golden-fronted Woodpecker",
                "Red-bellied Woodpecker",
                "Williamson’s Sapsucker",
                "Yellow-bellied Sapsucker",
                "Red-naped Sapsucker",
                "Red-breasted Sapsucker",
                "Ladder-backed Woodpecker",
                "Nuttall’s Woodpecker",
                "Downy Woodpecker",
                "Hairy Woodpecker",
                "Arizona Woodpecker",
                "White-headed Woodpecker",
                "Black-backed Woodpecker",
                "Northern Flicker",
                "American Kestrel",
                "Merlin",
                "Peregrine Falcon",
                "Prairie Falcon",
                "Northern Beardless-Tyrannulet",
                "Dusky-capped Flycatcher",
                "Ash-throated Flycatcher",
                "Brown-crested Flycatcher",
                "Great Kiskadee",
                "Sulphur-bellied Flycatcher",
                "Tropical Kingbird",
                "Cassin’s Kingbird",
                "Western Kingbird",
                "Eastern Kingbird",
                "Scissor-tailed Flycatcher",
                "Olive-sided Flycatcher",
                "Greater Pewee",
                "Western Wood-Pewee",
                "Willow Flycatcher",
                "Hammond’s Flycatcher",
                "Gray Flycatcher",
                "Dusky Flycatcher",
                "Pacific-slope Flycatcher",
                "Cordilleran Flycatcher",
                "Buff-breasted Flycatcher",
                "Black Phoebe",
                "Eastern Phoebe",
                "Say’s Phoebe",
                "Vermilion Flycatcher",
                "Loggerhead Shrike",
                "Northern Shrike",
                "Bell’s Vireo",
                "Hutton’s Vireo",
                "Cassin’s Vireo",
                "Blue-headed Vireo",
                "Plumbeous Vireo",
                "Warbling Vireo",
                "Red-eyed Vireo",
                "Yellow-green Vireo",
                "Green Jay",
                "Pinyon Jay",
                "Steller’s Jay",
                "Blue Jay",
                "Florida Scrub-Jay",
                "Island Scrub-Jay",
                "California Scrub-Jay",
                "Mexican Jay",
                "Clark’s Nutcracker",
                "Black-billed Magpie",
                "Yellow-billed Magpie",
                "American Crow",
                "Northwestern Crow",
                "Fish Crow",
                "Chihuahuan Raven",
                "Common Raven",
                "Horned Lark",
                "Purple Martin",
                "Tree Swallow",
                "Violet-green Swallow",
                "Northern Rough-winged Swallow",
                "Bank Swallow",
                "Cliff Swallow",
                "Cave Swallow",
                "Barn Swallow",
                "Mountain Chickadee",
                "Mexican Chickadee",
                "Chestnut-backed Chickadee",
                "Bridled Titmouse",
                "Oak Titmouse",
                "Black-crested Titmouse",
                "Verdin",
                "Bushtit",
                "Red-breasted Nuthatch",
                "White-breasted Nuthatch",
                "Pygmy Nuthatch",
                "Brown Creeper",
                "Rock Wren",
                "Canyon Wren",
                "House Wren",
                "Pacific Wren",
                "Marsh Wren",
                "Carolina Wren",
                "Bewick’s Wren",
                "Cactus Wren",
                "Blue-gray Gnatcatcher",
                "California Gnatcatcher",
                "Black-tailed Gnatcatcher",
                "American Dipper",
                "Golden-crowned Kinglet",
                "Ruby-crowned Kinglet",
                "Wrentit",
                "Western Bluebird",
                "Mountain Bluebird",
                "Townsend’s Solitaire",
                "Veery",
                "Gray-cheeked Thrush",
                "Swainson’s Thrush",
                "Hermit Thrush",
                "Wood Thrush",
                "American Robin",
                "Varied Thrush",
                "Gray Catbird",
                "Curve-billed Thrasher",
                "Brown Thrasher",
                "Long-billed Thrasher",
                "Bendire’s Thrasher",
                "California Thrasher",
                "Sage Thrasher",
                "Northern Mockingbird",
                "European Starling",
                "Cedar Waxwing",
                "Olive Warbler",
                "Northern Red Bishop",
                "Scaly-breasted Munia Finch",
                "House Sparrow",
                "Eastern Yellow Wagtail",
                "Red-throated Pipit",
                "American Pipit",
                "Pine Grosbeak",
                "House Finch",
                "Purple Finch",
                "Cassin’s Finch",
                "Red Crossbill",
                "Common Redpoll",
                "Pine Siskin",
                "Lesser Goldfinch",
                "Lawrence’s Goldfinch",
                "American Goldfinch",
                "Evening Grosbeak",
                "Lapland Longspur",
                "Chestnut-collared Longspur",
                "Snow Bunting",
                "McKay’s Bunting",
                "Ovenbird",
                "Worm-eating Warbler",
                "Northern Waterthrush",
                "Blue-winged Warbler",
                "Black-and-white Warbler",
                "Prothonotary Warbler",
                "Tennessee Warbler",
                "Orange-crowned Warbler",
                "Lucy’s Warbler",
                "Nashville Warbler",
                "MacGillivray’s Warbler",
                "Kentucky Warbler",
                "Common Yellowthroat",
                "Hooded Warbler",
                "American Redstart",
                "Cape May Warbler",
                "Magnolia Warbler",
                "Blackburnian Warbler",
                "Yellow Warbler",
                "Chestnut-sided Warbler",
                "Blackpoll Warbler",
                "Black-throated Blue Warbler",
                "Palm Warbler",
                "Pine Warbler",
                "Yellow-rumped Warbler",
                "Yellow-throated Warbler",
                "Grace’s Warbler",
                "Black-throated Gray Warbler",
                "Townsend’s Warbler",
                "Hermit Warbler",
                "Golden-cheeked Warbler",
                "Black-throated Green Warbler",
                "Canada Warbler",
                "Wilson’s Warbler",
                "Red-faced Warbler",
                "Painted Redstart",
                "Yellow-breasted Chat",
                "Olive Sparrow",
                "Green-tailed Towhee",
                "Spotted Towhee",
                "Eastern Towhee",
                "Rufous-crowned Sparrow",
                "Canyon Towhee",
                "California Towhee",
                "Abert’s Towhee",
                "Rufous-winged Sparrow",
                "Botteri’s Sparrow",
                "American Tree Sparrow",
                "Chipping Sparrow",
                "Clay-colored Sparrow",
                "Brewer’s Sparrow",
                "Black-chinned Sparrow",
                "Vesper Sparrow",
                "Lark Sparrow",
                "Black-throated Sparrow",
                "Bell’s Sparrow",
                "Sagebrush Sparrow",
                "Lark Bunting",
                "Savannah Sparrow",
                "Grasshopper Sparrow",
                "Nelson’s Sparrow",
                "Fox Sparrow",
                "Song Sparrow",
                "Lincoln’s Sparrow",
                "Swamp Sparrow",
                "White-throated Sparrow",
                "Harris’s Sparrow",
                "White-crowned Sparrow",
                "Golden-crowned Sparrow",
                "Dark-eyed Junco",
                "Yellow-eyed Junco",
                "Hepatic Tanager",
                "Summer Tanager",
                "Scarlet Tanager",
                "Western Tanager",
                "Flame-colored Tanager",
                "Northern Cardinal",
                "Pyrrhuloxia",
                "Rose-breasted Grosbeak",
                "Black-headed Grosbeak",
                "Blue Grosbeak",
                "Lazuli Bunting",
                "Indigo Bunting",
                "Varied Bunting",
                "Painted Bunting",
                "Bobolink",
                "Red-winged Blackbird",
                "Tricolored Blackbird",
                "Eastern Meadowlark",
                "Western Meadowlark",
                "Yellow-headed Blackbird",
                "Rusty Blackbird",
                "Brewer’s Blackbird",
                "Common Grackle",
                "Boat-tailed Grackle",
                "Great-tailed Grackle",
                "Bronzed Cowbird",
                "Brown-headed Cowbird",
                "Orchard Oriole",
                "Hooded Oriole",
                "Bullock’s Oriole",
                "Altamira Oriole",
                "Baltimore Oriole",
                "Scott’s Oriole",
  ]

  ANIMALS = [
      "parakeet",
      "mynah bird",
      "lemur",
      "salamander",
      "mouse",
      "camel",
      "rooster",
      "guanaco",
      "okapi",
      "bighorn",
      "squirrel",
      "impala",
      "gazelle",
      "starfish",
      "donkey",
      "cow",
      "sloth",
      "mule",
      "ibex",
      "woodchuck",
      "turtle",
      "mole",
      "bison",
      "sheep",
      "wolverine",
      "silver fox",
      "springbok",
      "elephant",
      "cheetah",
      "rabbit",
      "meerkat",
      "snowy owl",
      "koala",
      "hippopotamus",
      "ram",
      "iguana",
      "oryx",
      "finch",
      "bumble bee",
      "lovebird",
      "dung beetle",
      "parrot",
      "otter",
      "musk-ox",
      "muskrat",
      "jaguar",
      "lynx",
      "bat",
      "walrus",
      "warthog",
      "doe",
      "bunny",
      "burro",
      "blue crab",
      "gemsbok",
      "weasel",
      "whale",
      "civet",
      "antelope",
      "armadillo",
      "highland cow",
      "chinchilla",
      "argali",
      "shrew",
      "mare",
      "zebu",
      "frog",
      "hartebeest",
      "panther",
      "aardvark",
      "capybara",
      "eagle owl",
      "addax",
      "crocodile",
      "hamster",
      "wombat",
      "stallion",
      "ewe",
      "vicuna",
      "bear",
      "colt",
      "chimpanzee",
      "mink",
      "skunk",
      "ocelot",
      "wildcat",
      "gopher",
      "canary",
      "alpaca",
      "toad",
      "chamois",
      "giraffe",
      "chicken",
      "kitten",
      "kangaroo",
      "snake",
      "chipmunk",
      "guinea pig",
      "newt",
      "reindeer",
  ]

end
